### ISSUE TITLE
[Feat, Bug] 인가 구현 에러 발생

### ISSUE THREAD

**Issue by elyudwo** [inu-appcenter/server-study-15th#52]
## 📋 이슈 내용
인가 기능 구현 중 에러 발생

SecurityConfig 클래스 MyCustomDsl 메서드에서 JwtAuthorizationFilter를 추가하지 않을 경우 "/todos/**" uri 를 제외한 다른 uri 에 접근이 가능한데, 추가한 뒤 다른 uri로 접근하려고 하면 500 에러와 함께 콘솔창에서 java.lang.IllegalStateException: Cannot call sendError() after the response has been committe 에러를 뱉습니다.

위 에러는 데이터가 반복적으로 출력이 되는 무한 루프가 발생하는 순환 참조 오류라고 나옵니다.
JwtAuthorizationFilter 에서 데이터가 무한루프가 발생할 일이 없는데 왜 에러가 나오는지 궁금합니다

[SecurityConfig 에서 JwtAuthorizationFilter 추가했을 때]

![image](https://github.com/inu-appcenter/server-study-15th/assets/97587573/321b461d-62c3-462c-bba4-ada204610166)

![image](https://github.com/inu-appcenter/server-study-15th/assets/97587573/bbd89b53-5ad8-4b82-bbf3-e814116ec202)

![image](https://github.com/inu-appcenter/server-study-15th/assets/97587573/0e1e25db-f040-4cb7-ba92-481c1d5460a0)

[SecurityConfig 에서 JwtAuthorizationFilter 주석처리 했을때]

![image](https://github.com/inu-appcenter/server-study-15th/assets/97587573/01669f9b-2aa2-481b-b382-922c816db854)

![image](https://github.com/inu-appcenter/server-study-15th/assets/97587573/23eb7f44-c56e-4aed-9af1-1f03cb718a74)

![image](https://github.com/inu-appcenter/server-study-15th/assets/97587573/64582e1e-8036-494b-9292-9296eb176c2d)

컨트롤러에서 관리하지않는 uri 에 접근할 때, 404 NotFound 가 나와야하는데 JwtAuthorizationFilter를 걸어주면 사진과 같은 에러를 뱉으면서 500에러가 나옵니다.
그런데 JwtAuthorizationFilter를 사용하지 않을때는 404 NotFound가 잘 나오는데 이게 Json데이터랑 무슨 관련인지 이해가 안갑니다.

**Comment by Juser0** [comment]
코드 부분이나 실행 화면도 추가해주면 좋을 것 같아!

**Comment by Juser0** [comment]
@JsonIgnore 등의 어노테이션을 Todo의 User 참조하는 부분에 붙여서 응답을 받을 때 해당 프로퍼티를 null로 처리해버리거나
응답을 Entity가 아닌 DTO로 처리하는 방식을 사용하면 될 것 같아!

refs:
https://data-make.tistory.com/727

https://tecoble.techcourse.co.kr/post/2020-08-31-dto-vs-entity/
(이 글은 형도 읽고 댓글 달았던 글이더라...)

**Comment by elyudwo** [comment]
내 코드 모든 Controller에서 응답을 전부 Dto로 처리하는데 왜 에러가 발생하는지 모르겠어. 

실행 화면 추가했는데 다시 한번 봐줄 수 있을까??
